[CmdletBinding(DefaultParameterSetName='Validate')]
param(
 [Parameter(Mandatory=$true)][Alias('Image','镜像')][string]$PackagePath,
 [Parameter(ParameterSetName='Validate')][Alias('仅验证')][switch]$ValidateOnly,
 [Parameter(ParameterSetName='Apply')][Alias('应用')][switch]$Apply,
 [Alias('验证票据')][string]$ValidationTicket,
 [Alias('测试磁盘映像')][string]$TestDiskImage
)
# Fixed, data-only GKDUV1 interpreter.  Packages cannot carry executable code.
$ErrorActionPreference='Stop';Set-StrictMode -Version Latest
$Schema='gkd-mini-generic-update-v1';$TicketSchema='gkd-card-writer-ticket-v1'
$Magic=[byte[]](0x47,0x4b,0x44,0x55,0x56,0x31,0,0);$TrustAnchorSha256='b552155eeb5fd55cb699696957f52876e37a42fb436676fc43d9d089bf770ab8'
function Sha([byte[]]$b){$h=[Security.Cryptography.SHA256]::Create();try{([BitConverter]::ToString($h.ComputeHash($b))).Replace('-','').ToLowerInvariant()}finally{$h.Dispose()}}
function ReadExact($s,[int]$n){$b=New-Object byte[] $n;$i=0;while($i-lt$n){$r=$s.Read($b,$i,$n-$i);if($r-le0){throw 'short read'};$i+=$r};,$b}
function Bytes($p){$s=[IO.FileStream]::new($p,[IO.FileMode]::Open,[IO.FileAccess]::Read,[IO.FileShare]::Read);try{if($s.Length-gt[Int32]::MaxValue){throw 'file too large'};ReadExact $s ([int]$s.Length)}finally{$s.Dispose()}}
function U64($v,$n){if($v-isnot[string]-or$v-notmatch'^(0|[1-9][0-9]*)$'){throw "$n type"};[UInt64]::Parse($v,[Globalization.CultureInfo]::InvariantCulture)}
function AssertHash($v,$n){if($v-isnot[string]-or$v-notmatch'^[0-9a-f]{64}$'){throw "$n hash"}}
function Keys($o,[string[]]$k,$n){if($null-eq$o){throw "$n missing"};$a=@($o.psobject.Properties.Name);if($a.Count-ne$k.Count-or@($a|?{$k-cnotcontains$_}).Count){throw "$n keys"}}
function Stage($InputPath){$x=Get-Item -LiteralPath $InputPath -Force;if($x.PSIsContainer -or ($x.Attributes -band [IO.FileAttributes]::ReparsePoint)){throw 'package must be one ordinary file'};$d=Join-Path ([IO.Path]::GetTempPath()) ('GKDCardWriter-'+[Guid]::NewGuid().ToString('N'));[IO.Directory]::CreateDirectory($d)|Out-Null;$p=Join-Path $d 'package.gkdupdate';[IO.File]::Copy($x.FullName,$p,$false);[pscustomobject]@{D=$d;P=$p}}
function Trust(){ $p=Join-Path $PSScriptRoot 'trust-anchor.xml';$i=Get-Item -LiteralPath $p -Force;if($i.PSIsContainer-or($i.Attributes-band[IO.FileAttributes]::ReparsePoint)){throw 'trust anchor unsafe'};$b=Bytes $p;if((Sha $b)-cne$TrustAnchorSha256){throw 'trust anchor pin differs'};$x=[Text.Encoding]::UTF8.GetString($b).Trim();if($x-notmatch'^<RSAKeyValue><Modulus>[A-Za-z0-9+/=]+</Modulus><Exponent>AQAB</Exponent></RSAKeyValue>$'){throw 'trust anchor format'};$x }
function Package($p){
 $r=Bytes $p;if($r.Length-lt268){throw 'container short'};for($i=0;$i-lt8;$i++){if($r[$i]-ne$Magic[$i]){throw 'container magic'}};$n=[BitConverter]::ToUInt32($r,8);if($n-lt2-or$n-gt4194304-or(12+$n+256)-gt$r.Length){throw 'manifest bound'}
 $m=New-Object byte[] ([int]$n);$sig=New-Object byte[] 256;[Array]::Copy($r,12,$m,0,$n);[Array]::Copy($r,12+$n,$sig,0,256);try{$s=[Text.Encoding]::UTF8.GetString($m)|ConvertFrom-Json}catch{throw 'manifest json'};Keys $s @('components','disk','packs','protocol','schema','version') 'manifest';if($s.schema-cne$Schema-or$s.version-ne1){throw 'schema'}
 $rsa=[Security.Cryptography.RSA]::Create();$rsa.FromXmlString((Trust));try{if(-not$rsa.VerifyData($m,$sig,[Security.Cryptography.HashAlgorithmName]::SHA256,[Security.Cryptography.RSASignaturePadding]::Pkcs1)){throw 'untrusted package signature'}}finally{$rsa.Dispose()}
 Keys $s.packs @('after','before','block_size') 'packs';$bs=U64 $s.packs.block_size 'block size';if($bs-notin512,1024,2048,4096){throw 'block size'};foreach($q in 'before','after'){Keys $s.packs.$q @('bytes','sha256') "$q pack";if((U64 $s.packs.$q.bytes "$q size")-gt536870912){throw 'pack bound'};AssertHash $s.packs.$q.sha256 "$q pack"};$bn=U64 $s.packs.before.bytes 'before size';$an=U64 $s.packs.after.bytes 'after size';if($bn-ne$an-or$bn%$bs-ne0-or([UInt64](12+$n+256)+$bn+$an)-ne[UInt64]$r.Length){throw 'container length'}
 $b=New-Object byte[] ([int]$bn);$a=New-Object byte[] ([int]$an);[Array]::Copy($r,12+$n+256,$b,0,$bn);[Array]::Copy($r,12+$n+256+$bn,$a,0,$an);if((Sha $b)-cne$s.packs.before.sha256-or(Sha $a)-cne$s.packs.after.sha256){throw 'pack hash'}
 Keys $s.disk @('identity','mbr_sha256','partition_geometry') 'disk';Keys $s.disk.identity @('disk_bytes','disk_number','mbr_sha256','p2_uuid') 'identity';Keys $s.disk.partition_geometry @('logical_block_bytes','p2_bytes','p2_offset') 'geometry';foreach($q in $s.disk.mbr_sha256,$s.disk.identity.mbr_sha256){AssertHash $q 'mbr'};if($s.disk.mbr_sha256-cne$s.disk.identity.mbr_sha256){throw 'mbr disagreement'};$disk=U64 $s.disk.identity.disk_bytes 'disk bytes';$po=U64 $s.disk.partition_geometry.p2_offset 'p2 offset';$pb=U64 $s.disk.partition_geometry.p2_bytes 'p2 bytes';if($po+$pb-gt$disk-or(U64 $s.disk.partition_geometry.logical_block_bytes 'logical block')-ne$bs){throw 'geometry'}
 Keys $s.protocol @('apply_order','launcher_last','max_run_bytes','rollback_order','runs') 'protocol';if(-not$s.protocol.launcher_last-or(U64 $s.protocol.max_run_bytes 'run cap')-gt8388608){throw 'commit protocol'};$all=@();$data=@();$l=@();foreach($c in @($s.components)){Keys $c @('id','kind','mapped_blocks','preserve','source_sha256','target_sha256') 'component';if($c.id-isnot[string]-or$c.id-notmatch'^[a-z0-9][a-z0-9_-]{0,63}$'-or$c.kind-cnotin'data','launcher'){throw 'component'};AssertHash $c.source_sha256 'source';AssertHash $c.target_sha256 'target';Keys $c.preserve @('meaning','raw_sha256') 'preserve';if($c.kind-ceq'launcher'){$l+=,$c}else{$data+=,$c};foreach($z in @($c.mapped_blocks)){Keys $z @('after_sha256','before_sha256','offset','pack_index') 'block';$o=U64 $z.offset 'offset';$ix=U64 $z.pack_index 'index';if($o%$bs-ne0-or$o-lt$po-or$o+$bs-gt$po+$pb-or$ix-ge($bn/$bs)){throw 'block map'};AssertHash $z.before_sha256 'before';AssertHash $z.after_sha256 'after';$all+=,[pscustomobject]@{C=$c;B=$z}}
 };if($l.Count-ne1-or$data.Count-lt1-or$all.Count-ne($bn/$bs)){throw 'coverage'};$ii=@($all|%{[int](U64 $_.B.pack_index 'index')}|sort);for($i=0;$i-lt$ii.Count;$i++){if($ii[$i]-ne$i){throw 'pack coverage'}};$reverse=@($data|%{$_.id});[Array]::Reverse($reverse);if((@($s.protocol.apply_order)-join',')-cne(@($data|%{$_.id})-join',')-or(@($s.protocol.rollback_order)-join',')-cne(@($l[0].id)+$reverse-join',')){throw 'order'}
 foreach($e in $all){$i=[int](U64 $e.B.pack_index 'index')*[int]$bs;if((Sha $b[$i..($i+$bs-1)])-cne$e.B.before_sha256-or(Sha $a[$i..($i+$bs-1)])-cne$e.B.after_sha256){throw 'block pack hash'}};[pscustomobject]@{S=$s;B=$b;A=$a;BS=[int]$bs;D=$data;L=$l[0];SHA=(Sha $r)}
}
function CH($s,$c,$bs){$h=[Security.Cryptography.SHA256]::Create();try{foreach($b in @($c.mapped_blocks|sort{[UInt64]$_.pack_index})){$s.Position=[Int64](U64 $b.offset 'offset');$x=ReadExact $s $bs;$h.TransformBlock($x,0,$x.Length,$null,0)|Out-Null};$h.TransformFinalBlock([byte[]]@(),0,0)|Out-Null;([BitConverter]::ToString($h.Hash)).Replace('-','').ToLowerInvariant()}finally{$h.Dispose()}}
function Source($s,$p){if([UInt64]$s.Length-ne(U64 $p.S.disk.identity.disk_bytes 'disk bytes')){throw 'disk geometry differs'};$s.Position=0;if((Sha(ReadExact $s 512))-cne$p.S.disk.mbr_sha256){throw 'MBR differs'};foreach($c in $p.S.components){if((CH $s $c $p.BS)-cne$c.source_sha256){throw "source differs: $($c.id)"}}}
function Target($s,$p){foreach($c in $p.S.components){if((CH $s $c $p.BS)-cne$c.target_sha256){throw "target differs: $($c.id)"}};$s.Position=0;if((Sha(ReadExact $s 512))-cne$p.S.disk.mbr_sha256){throw 'MBR differs'}}
function Put($s,$p,$c,$after){$q=if($after){$p.A}else{$p.B};foreach($b in @($c.mapped_blocks|sort{[UInt64]$_.offset})){$at=[int](U64 $b.pack_index 'index')*$p.BS;$s.Position=[Int64](U64 $b.offset 'offset');$s.Write($q,$at,$p.BS)};$s.Flush()}
# Commit protocol invariant: launcher must be last; rollback restores it first.
function TestApply($path,$p){$x=Get-Item -LiteralPath $path -Force;if($x.PSIsContainer -or ($x.Attributes -band [IO.FileAttributes]::ReparsePoint)){throw 'test image unsafe'};$s=[IO.FileStream]::new($x.FullName,[IO.FileMode]::Open,[IO.FileAccess]::ReadWrite,[IO.FileShare]::None,1048576,[IO.FileOptions]::WriteThrough);try{Source $s $p;try{foreach($c in $p.D){Put $s $p $c $true};Put $s $p $p.L $true;Target $s $p}catch{try{Put $s $p $p.L $false;for($i=$p.D.Count-1;$i -ge 0;$i--){Put $s $p $p.D[$i] $false};Source $s $p}catch{};throw}}finally{$s.Dispose()}}
function Ticket($path,$p){$x=[ordered]@{schema=$TicketSchema;package_sha256=$p.SHA;nonce=[Guid]::NewGuid().ToString('N');validated_utc=[DateTime]::UtcNow.ToString('o');ttl_seconds=900};$r=[Text.Encoding]::UTF8.GetBytes(($x|ConvertTo-Json -Compress));[IO.File]::WriteAllBytes($path,$r);[pscustomobject]@{X=$x;H=(Sha $r)}}
function CheckTicket($path,$p){$r=Bytes $path;try{$x=[Text.Encoding]::UTF8.GetString($r)|ConvertFrom-Json}catch{throw 'ticket json'};Keys $x @('nonce','package_sha256','schema','ttl_seconds','validated_utc') 'ticket';if($x.schema-cne$TicketSchema-or$x.package_sha256-cne$p.SHA-or$x.nonce-notmatch'^[0-9a-f]{32}$'-or$x.ttl_seconds-lt1-or$x.ttl_seconds-gt900){throw 'ticket differs'};if(([DateTime]::UtcNow-[DateTime]::Parse($x.validated_utc).ToUniversalTime()).TotalSeconds-gt$x.ttl_seconds){throw 'ticket expired'}}
$stage=$null;try{$stage=Stage $PackagePath;$p=Package $stage.P;if($Apply){if(-not $ValidationTicket){throw 'apply requires -验证票据 from validation'};CheckTicket $ValidationTicket $p;if($TestDiskImage){TestApply $TestDiskImage $p;[pscustomobject]@{schema=$Schema;status='TEST_IMAGE_APPLIED_AND_VERIFIED';launcher_committed_last=$true;full_component_readback=$true}|ConvertTo-Json -Compress;return};throw 'physical Apply fail-closed: durable journal/recovery is not implemented; no device was opened'};if($TestDiskImage){$s=[IO.FileStream]::new((Get-Item -LiteralPath $TestDiskImage).FullName,[IO.FileMode]::Open,[IO.FileAccess]::Read,[IO.FileShare]::Read);try{Source $s $p}finally{$s.Dispose()}};if(-not $ValidationTicket){$ValidationTicket=Join-Path ([IO.Path]::GetTempPath()) ('GKD-validation-'+[Guid]::NewGuid().ToString('N')+'.json')};$t=Ticket $ValidationTicket $p;[pscustomobject]@{schema=$Schema;status='VALIDATED';package_sha256=$p.SHA;validation_ticket=$ValidationTicket;validation_ticket_sha256=$t.H;nonce=$t.X.nonce;ttl_seconds=900}|ConvertTo-Json -Compress}finally{if($stage -and [IO.Directory]::Exists($stage.D)){[IO.Directory]::Delete($stage.D,$true)}}
