#!/bin/sh
set -eu
PATH=/sbin:/bin:/usr/sbin:/usr/bin
export GKD_CONFIG_SCHEMA=/etc/gkd-mini/gdkmini.schema
export GKD_CONFIG_MERGER=/usr/lib/gkd-config-merge.awk
export GKD_CONFIG_OVERRIDE=/run/gkd-application/config.override.conf
export GKD_CONFIG_RUN_DIR=/run/gkd-config
export GKD_CONFIG_STATE_DIR=/run/gkd-config-state
export GKD_CONFIG_RENAME=/usr/sbin/gkd-config-rename
mkdir -p /var/log /var/run /var/tmp
exec >>/var/log/gkd-application.log 2>&1
echo GKD_APPLICATION_PROFILE=application-a
# Reuse the accepted sealed transaction engine before application mounts exist.
set +e
/usr/sbin/gkd-application-service --update-boot
update_status=$?
set -e
case "$update_status" in
    0) exec /usr/sbin/gkd-application-service ;;
    10|20)
        sync
        /bin/busybox reboot -f
        echo GKD_APP_BLOCKED=reboot-returned
        exit 1
        ;;
    *) echo GKD_APP_BLOCKED=update-boot; exit 1 ;;
esac
