#!/usr/bin/env python3
from __future__ import annotations

import argparse
import hashlib
import json
import os
from pathlib import Path
import re
import subprocess


ROOT = Path(__file__).resolve().parents[1]
MANIFEST = ROOT / "initramfs/ram-payload-manifest.json"
HEADER = ROOT / "initramfs/round83-ram-payload.generated.h"
FIXED_MTIME = 1785448800


class ClosureError(RuntimeError):
    pass


def sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as stream:
        for block in iter(lambda: stream.read(8 * 1024 * 1024), b""):
            digest.update(block)
    return digest.hexdigest()


def debugfs(image: Path, request: str) -> str:
    result = subprocess.run(
        ["debugfs", "-R", request, str(image)],
        check=False,
        capture_output=True,
        text=True,
        timeout=30,
    )
    if result.returncode:
        raise ClosureError("debugfs rejected " + request.split()[0])
    return result.stdout


def c_hash(value: str) -> str:
    return ",".join("0x" + value[index:index + 2] for index in range(0, 64, 2))


def c_string(value: str) -> str:
    return json.dumps(value, ensure_ascii=True)


def render_header(manifest: dict, banner: str =
                  "Generated by Round83 derive-ram-payload.py; do not hand edit.") -> str:
    files = [
        "\t{%s,%s,%d,%s,%s,{%s}}" % (
            c_string(item["source"]), c_string(item["destination"]), item["bytes"],
            item["source_mode"], item["destination_mode"], c_hash(item["sha256"]),
        )
        for item in manifest["p1_regular_files"]
    ]
    links = [
        "\t{%s,%s,%s,%d}" % (
            c_string(item["source"]), c_string(item["destination"]),
            c_string(item["target"]), 1 if item["source_required"] else 0,
        )
        for item in manifest["p1_symlinks"]
    ]
    return "\n".join((
        f"/* {banner} */",
        "#ifndef GKD_ROUND83_RAM_PAYLOAD_GENERATED_H",
        "#define GKD_ROUND83_RAM_PAYLOAD_GENERATED_H",
        "#define R64M_PAYLOAD_FINAL 1",
        f'#define R64M_PAYLOAD_CANONICAL_TREE_SHA256 "{manifest["dependency_tree_sha256"]}"',
        f'#define R64M_PAYLOAD_PREFLIGHT_TREE_SHA256 "{manifest["dependency_tree_sha256"]}"',
        "static const struct r64m_file r64m_final_p1_files[] = {",
        ",\n".join(files), "};",
        "static const struct r64m_link r64m_final_p1_links[] = {",
        ",\n".join(links), "};",
        "static const struct r64m_payload r64m_final_payload = {",
        "\tr64m_final_p1_files, sizeof(r64m_final_p1_files) / sizeof(r64m_final_p1_files[0]),",
        "\tr64m_final_p1_links, sizeof(r64m_final_p1_links) / sizeof(r64m_final_p1_links[0])",
        "};", "#endif", "",
    ))


def verify_regular(image: Path, item: dict, temporary: Path) -> None:
    output = debugfs(image, "stat " + item["source"])
    mode = re.search(r"Mode:\s+0*([0-7]+)", output)
    uid = re.search(r"User:\s+(\d+)", output)
    gid = re.search(r"Group:\s+(\d+)", output)
    size = re.search(r"Size:\s+(\d+)", output)
    if "Type: regular" not in output or not mode or not uid or not gid or not size:
        raise ClosureError("regular dependency missing: " + item["source"])
    if int(uid.group(1)) != item["uid"] or int(gid.group(1)) != item["gid"]:
        raise ClosureError("owner drift: " + item["source"])
    if int(size.group(1)) != item["bytes"] or int(mode.group(1), 8) != int(item["source_mode"], 8):
        raise ClosureError("mode or size drift: " + item["source"])
    target = temporary / item["source"].lstrip("/")
    target.parent.mkdir(parents=True, exist_ok=True)
    debugfs(image, f"dump {item['source']} {target}")
    if sha256(target) != item["sha256"]:
        raise ClosureError("content drift: " + item["source"])
    os.utime(target, (FIXED_MTIME, FIXED_MTIME), follow_symlinks=False)


def verify_symlink(image: Path, item: dict) -> None:
    if not item["source_required"]:
        return
    output = debugfs(image, "stat " + item["source"])
    target = re.search(r'Fast link dest:\s+"([^"]+)"', output)
    if "Type: symlink" not in output or not target or target.group(1) != item["target"]:
        raise ClosureError("symlink drift: " + item["source"])


def initramfs_entry(value: str) -> str:
    if not value.startswith("/") or any(character.isspace() for character in value):
        raise ClosureError("unsafe initramfs path: " + value)
    return value


def render_initramfs(manifest: dict, temporary: Path) -> str:
    directories: dict[str, int] = {
        "/bin": 0o755,
        "/sbin": 0o755,
        "/lib": 0o755,
        "/etc": 0o755,
        "/usr": 0o755,
    }
    destinations = [item["destination"] for item in manifest["p1_regular_files"]]
    destinations += [item["destination"] for item in manifest["p1_symlinks"]]
    for destination in destinations:
        current = Path(initramfs_entry(destination)).parent
        while str(current) != "/":
            directories.setdefault(str(current), 0o755)
            current = current.parent
    lines = ["# Verified frozen RC3.4 recovery userspace embedded in initramfs."]
    for directory in sorted(directories, key=lambda value: (value.count("/"), value)):
        lines.append(f"dir {directory} {directories[directory]:04o} 0 0")
    for item in manifest["p1_regular_files"]:
        source = temporary / item["source"].lstrip("/")
        destination = initramfs_entry(item["destination"])
        lines.append(
            f"file {destination} {source} {int(item['destination_mode'], 8):04o} 0 0"
        )
    for item in manifest["p1_symlinks"]:
        destination = initramfs_entry(item["destination"])
        target = item["target"]
        if any(character.isspace() for character in target):
            raise ClosureError("unsafe initramfs symlink: " + destination)
        lines.append(f"slink {destination} {target} 0777 0 0")
    return "\n".join(lines) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--p1", required=True, type=Path)
    parser.add_argument("--temporary", required=True, type=Path)
    parser.add_argument("--initramfs-list", type=Path)
    parser.add_argument("--derived-header", type=Path)
    parser.add_argument("--exclude-regular", action="append", default=[])
    parser.add_argument("--extra-manifest", type=Path)
    arguments = parser.parse_args()
    manifest = json.loads(MANIFEST.read_text(encoding="utf-8"))
    if render_header(manifest) != HEADER.read_text(encoding="utf-8"):
        raise SystemExit("GKD_CURRENT_RAM_CLOSURE=BLOCKED header-manifest-drift")
    if arguments.exclude_regular and not arguments.derived_header:
        raise SystemExit("GKD_CURRENT_RAM_CLOSURE=BLOCKED derived-header-required")
    if arguments.derived_header and arguments.derived_header.exists():
        raise SystemExit("GKD_CURRENT_RAM_CLOSURE=BLOCKED derived-header-exists")
    arguments.temporary.mkdir(parents=True, exist_ok=False)
    try:
        for item in manifest["p1_regular_files"]:
            verify_regular(arguments.p1, item, arguments.temporary)
        if arguments.extra_manifest:
            extra = json.loads(arguments.extra_manifest.read_text(encoding="utf-8"))
            for item in extra["p1_regular_files"]:
                verify_regular(arguments.p1, item, arguments.temporary)
            for item in extra.get("p1_symlinks", []):
                verify_symlink(arguments.p1, item)
        for item in manifest["p1_symlinks"]:
            verify_symlink(arguments.p1, item)
        if arguments.derived_header:
            excluded = set(arguments.exclude_regular)
            for path in excluded:
                if not path.startswith("/") or sum(
                    item["destination"] == path
                    for item in manifest["p1_regular_files"]
                ) != 1:
                    raise ClosureError("invalid regular exclusion: " + path)
            derived = dict(manifest)
            derived["p1_regular_files"] = [
                item for item in manifest["p1_regular_files"]
                if item["destination"] not in excluded
            ]
            arguments.derived_header.write_text(
                render_header(
                    derived,
                    "Generated verified recovery payload subset; do not hand edit.",
                ),
                encoding="utf-8",
            )
        if arguments.initramfs_list:
            if arguments.initramfs_list.exists():
                raise ClosureError("initramfs list already exists")
            arguments.initramfs_list.write_text(
                render_initramfs(manifest, arguments.temporary), encoding="utf-8"
            )
    except ClosureError as exc:
        raise SystemExit("GKD_CURRENT_RAM_CLOSURE=BLOCKED " + str(exc)) from exc
    print(
        "GKD_CURRENT_RAM_CLOSURE=PASS files=%d links=%d tree=%s" % (
            len(manifest["p1_regular_files"]), len(manifest["p1_symlinks"]),
            manifest["dependency_tree_sha256"],
        )
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
